# Generated by Django 3.1.7 on 2021-03-25 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, verbose_name='Session id пользователя')),
                ('original_url', models.URLField(verbose_name='Оригинальный URL')),
                ('url_subpart', models.CharField(max_length=32, unique=True, validators=[
                    django.core.validators.RegexValidator(code='nomatch',
                                                          message='Subpart has to be at least 3 characters long',
                                                          regex='^.{3,32}$')], verbose_name='URL subpart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
