# Generated by Django 3.1.7 on 2021-04-24 06:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Оригинальный URL')),
                ('url_subpart', models.CharField(blank=True, max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message="Subpart must be at least 3 characters long and mustn't contain any symbols but `-` or `_`", regex='^[A-Za-z0-9-_]{3,32}$')], verbose_name='URL subpart')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания url правила')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session', verbose_name='Session пользователя')),
            ],
        ),
    ]
