# Generated by Django 3.1.7 on 2021-03-26 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='SET GLOBAL event_scheduler = ON;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql="""CREATE EVENT remove_old_urls
                 ON SCHEDULE EVERY 1 DAY
                 DO DELETE FROM core_url
                 WHERE created_at < NOW() - INTERVAL 7 DAY;""",
            reverse_sql=migrations.RunSQL.noop
        )
    ]
