# Generated by Django 3.1.7 on 2021-03-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('core', '0002_auto_20210326_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='session_id',
        ),
        migrations.AddField(
            model_name='url',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session', verbose_name='Session пользователя'),
        ),
    ]
